### PR TITLE
Add AGPLv3 LICENSE

### PR DESCRIPTION
**Pull request by katlol**
@fcbarros @Micky-G as you two have contributed to the repos so far, your approval by way of a comment would be good to license the current repo as AGPLv3.

### CODE REVIEW

**Comment by Micky-G** [comment]
Fine by me, thanks @katlol.

**Review by Micky-G — COMMENTED** [review]
Fine by me, thanks @katlol

**Review by jdmaudio — COMMENTED** [review]
Looks good. Thanks

**Review by fcbarros — APPROVED** [review]
License as specified, approved

**Pull request merged**
